### ISSUE TITLE
node_util.py + config_from_example.sh should avoid IPv6 for IP detection

### ISSUE THREAD

**Issue by GuybrushX** [casper-network/casper-node-launcher#44]
The following service is one of the used services to detect the external IP address:
```shell
$ nslookup ident.me
Server:         127.0.0.53
Address:        127.0.0.53#53

Non-authoritative answer:
Name:   ident.me
Address: 49.12.234.183
Name:   ident.me
Address: 2a01:4f8:c0c:bd0a::1
```

It is the only one resolving to an IPv6 address as well.

`node_util.py` seems to use the IPv6 first but on hosts not configured for IPv6 the DNS lookup can take quite some time and it seems that it is stuck.

`config_from_example.sh` is using the same service but it is marked as deprecated and it's using curl.

How to fix:
`curl` can easily be changed to force IPv4 only:
```shell
curl -4 https://ident.me
```

I'm not a python expert and I didn't find a quick and clean solution.

**Comment by RitaMAllenCA** [comment]
@sacherjj can you advise?

**Comment by sacherjj** [comment]
I would have to look into this. Not sure people actually use IP6 for most things.

**Comment by GuybrushX** [comment]
I agree, most probably don't use IPv6 but hosting providers/OSes enable it and if it's not configured properly (missing gateway for example) it causes such issues.

I think IPv6 also isn't supported by the Casper Node (is it?) so I think it should be totally safe to just disable it for the tools as well. Maybe the IP check would even fail if ident.me would return IPv6 first?

**Comment by GuybrushX** [comment]
Can you explain why this was closed without any comment please?

It looks like this is still an issue and wasn't fixed yet?

With the current upgrade to 1.5.2 one node operator got a broken/inconsistent system because the upgrade exited because 2 of the used sites within `node_util.py` returned IPv6 addresses instead of IPv4:
- https://checkip.amazonaws.com -> returned IPv4
- https://ifconfig.me -> returned IPv6
- https://ident.me -> returned IPv6

Not sure if the Amazon service can be configured to return IPv4 only or if it does already.

After some more digging around and investigation here are a few possible fixes for both, Python and curl:
- change https://ident.me to https://4.ident.me
- replace https://ifconfig.me with another tool which supports specific IPv4 lookup, e. g. https://ipv4.icanhazip.com/ (run by Cloudflare nowadays)
- check if amazonaws can be configured to use IPv4 only as well, skip or replace it with another tool like https://api.ipify.org
