### ISSUE TITLE
Installed binaries don't match config

### ISSUE THREAD

**Issue by 0x70313335** [casper-network/casper-node-launcher#45]
I didn't had any problems installing the node and executing the commands up until to the point where i want to start the node-launcher service.

I get an error in the log files which is something like.
"Installed binary version (1_0_0) don't match installed configs (1_0_0, 1_1_0, 1_1_2 etc..) 
I'm on a ESXi VM but the installed Ubuntu is 20.04.

When i try to curl the debug_file on cnm labs the vm just crashes. But it's not a resource Problem since it has 64 gb of ram and 12 cores.

Doesn't seem like an issue on my end but i could be wrong. Already asked in Discord and Telegram but without any results.

**Comment by sacherjj** [comment]
This is because the protocols were not staged correctly.  You should use `/etc/casper/node_util.py stage_protocols [network conf]` to pull these down in sequence.
